#!/usr/bin/env bash

echo '# These rules ensure that physical interfaces are mapped correctly to names' > /etc/udev/rules.d/70-persistent-net.rules
if  strings /dev/mtd3 | grep -w 'modelNumber=WRT1900AC' >> /dev/null  &&  strings /dev/mtd3 | grep 'hw_revision=1' >>  /dev/null
then
	# Interfaces are reversed on WRT1900AC V1
	ifindex_eth0=3
	ifindex_eth1=2
	ifindex_wlan0=5
	ifindex_wlan1=4

	echo "SUBSYSTEM==\"net\", ATTR{ifindex}==\"${ifindex_eth0}\", NAME=\"eth0\"" >> /etc/udev/rules.d/70-persistent-net.rules
	echo "SUBSYSTEM==\"net\", ATTR{ifindex}==\"${ifindex_eth1}\", NAME=\"eth1\"" >> /etc/udev/rules.d/70-persistent-net.rules
	echo "SUBSYSTEM==\"net\", ATTR{ifindex}==\"${ifindex_wlan0}\", NAME=\"wlan0\"" >> /etc/udev/rules.d/70-persistent-net.rules
	echo "SUBSYSTEM==\"net\", ATTR{ifindex}==\"${ifindex_wlan1}\", NAME=\"wlan1\"" >> /etc/udev/rules.d/70-persistent-net.rules
elif strings /dev/mtd3 | grep -w 'modelNumber=WRT3200ACM' >> /dev/null 
then 
	# Interface mapping on a WRT3200ACM  
	ifindex_eth0=3 
	ifindex_eth1=2 
	ifindex_wlan0=5 
	ifindex_wlan1=6 
	ifindex_mlan0=4

	echo "SUBSYSTEM==\"net\", ATTR{ifindex}==\"${ifindex_eth0}\", NAME=\"eth0\"" >> /etc/udev/rules.d/70-persistent-net.rules
        echo "SUBSYSTEM==\"net\", ATTR{ifindex}==\"${ifindex_eth1}\", NAME=\"eth1\"" >> /etc/udev/rules.d/70-persistent-net.rules
        echo "SUBSYSTEM==\"net\", ATTR{ifindex}==\"${ifindex_wlan0}\", NAME=\"wlan0\"" >> /etc/udev/rules.d/70-persistent-net.rules
        echo "SUBSYSTEM==\"net\", ATTR{ifindex}==\"${ifindex_wlan1}\", NAME=\"wlan1\"" >> /etc/udev/rules.d/70-persistent-net.rules
	echo "SUBSYSTEM==\"net\", ATTR{ifindex}==\"${ifindex_mlan0}\", NAME=\"mlan0\"" >> /etc/udev/rules.d/70-persistent-net.rules
else
	# Interface mapping on a WRT1200AC, WRT1900AC V2 and WRT1900ACS
	ifindex_eth0=3
	ifindex_eth1=2
	ifindex_wlan0=4
	ifindex_wlan1=5

	echo "SUBSYSTEM==\"net\", ATTR{ifindex}==\"${ifindex_eth0}\", NAME=\"eth0\"" >> /etc/udev/rules.d/70-persistent-net.rules
        echo "SUBSYSTEM==\"net\", ATTR{ifindex}==\"${ifindex_eth1}\", NAME=\"eth1\"" >> /etc/udev/rules.d/70-persistent-net.rules
        echo "SUBSYSTEM==\"net\", ATTR{ifindex}==\"${ifindex_wlan0}\", NAME=\"wlan0\"" >> /etc/udev/rules.d/70-persistent-net.rules
        echo "SUBSYSTEM==\"net\", ATTR{ifindex}==\"${ifindex_wlan1}\", NAME=\"wlan1\"" >> /etc/udev/rules.d/70-persistent-net.rules
fi
exit 0
