#!/bin/sh

ETH0MAC=`strings /dev/mtd3|grep hw_mac_addr|cut -d= -f2`

if [ ! $ETH0MAC ]
then
	echo "mcdebian: Devinfo is corrupted, no MAC Address found" > /dev/kmsg
else
	echo "mcdebian: Setting br0 MAC Address: $ETH0MAC" > /dev/kmsg
	ip link set dev br0 address $ETH0MAC
fi
